UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Barrios populares (RENABAP)';
UPDATE metric SET mtr_icon='fas fa-bolt' WHERE mtr_caption='Modo de acceso a los servicios en Barrios Populares';
UPDATE metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Comedores y merenderos comunitarios (ReNaCoM)';
UPDATE metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Población total';
UPDATE metric SET mtr_icon='fas fa-tint' WHERE mtr_caption='Acceso a agua de red';
UPDATE metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Densidad de población';
UPDATE metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Necesidades básicas insatisfechas (NBI)';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de educación común';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de educación común';
UPDATE metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Redes de colectivo';
UPDATE metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Provincias';
UPDATE metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Municipios';
UPDATE metric SET mtr_icon='fas fa-landmark' WHERE mtr_caption='Gobiernos locales';
UPDATE metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Regiones';
UPDATE metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Departamentos';
UPDATE metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Regiones y zonas sanitarias';
UPDATE metric SET mtr_icon='fas fa-mail-bulk' WHERE mtr_caption='Códigos postales (4 dígitos)';
UPDATE metric SET mtr_icon='fas fa-balance-scale' WHERE mtr_caption='Regiones judiciales';
UPDATE metric SET mtr_icon='fas fa-balance-scale' WHERE mtr_caption='Circunscripciones judiciales';
UPDATE metric SET mtr_icon='fas fa-city' WHERE mtr_caption='Aglomerados';
UPDATE metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Zonas del conurbano bonaerense';
UPDATE metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Barrios';
UPDATE metric SET mtr_icon='fas fa-map-pin' WHERE mtr_caption='Localidades';
UPDATE metric SET mtr_icon='fas fa-cloud-sun' WHERE mtr_caption='Climas';
UPDATE metric SET mtr_icon='fas fa-cloud' WHERE mtr_caption='Climas agrupados';
UPDATE metric SET mtr_icon='fas fa-leaf' WHERE mtr_caption='Eco-regiones';
UPDATE metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Sistemas de cuencas';
UPDATE metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Cuencas y regiones hídricas';
UPDATE metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Se reconoce indígena y habla o entiende la lengua de ese pueblo (censo)';
UPDATE metric SET mtr_icon='fas fa-box' WHERE mtr_caption='Disponibilidad de bienes';
UPDATE metric SET mtr_icon='fas fa-broom' WHERE mtr_caption='Hogares con servicio doméstico sin retiro (con cama)';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Jefatura del hogar';
UPDATE metric SET mtr_icon='fas fa-child' WHERE mtr_caption='Niños/as y adolescentes por edad';
UPDATE metric SET mtr_icon='fas fa-user' WHERE mtr_caption='Población adulta por edad';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tamaño de hogar';
UPDATE metric SET mtr_icon='fas fa-venus' WHERE mtr_caption='Tasa de feminidad';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tipo de hogar';
UPDATE metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Población afrodescendiente';
UPDATE metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Población pueblos originarios (censo)';
UPDATE metric SET mtr_icon='fas fa-layer-group' WHERE mtr_caption='Estrato socioeconómico';
UPDATE metric SET mtr_icon='fas fa-exclamation-circle' WHERE mtr_caption='Incidencia del riesgo de exclusión';
UPDATE metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Riesgo de inseguridad alimentaria';
UPDATE metric SET mtr_icon='fas fa-comment' WHERE mtr_caption='Hablan alguna lengua indígena en el hogar';
UPDATE metric SET mtr_icon='fas fa-chart-line' WHERE mtr_caption='Población proyectada por departamento';
UPDATE metric SET mtr_icon='fas fa-coins' WHERE mtr_caption='Pobreza crónica';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Asistencia a educación formal';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Jefes con secundaria completa o más';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Nivel educativo de la población';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Nivel educativo de los jefes';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Niños y adolescentes que no asisten a instituciones educativas formales';
UPDATE metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Población mayor de edad sin estudios secundarios completos';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de educación especial';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de jóvenes y adultos';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de educación especial';
UPDATE metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de jóvenes y adultos';
UPDATE metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Establecimientos con educación intercultural bilingüe';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Establecimientos de nivel inicial común';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Establecimientos de nivel inicial de educación especial';
UPDATE metric SET mtr_icon='fas fa-university' WHERE mtr_caption='Establecimientos de nivel superior';
UPDATE metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Matrícula (alumnos) de educación intercultural bilingüe';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Matrícula (alumnos) de nivel inicial de educación común';
UPDATE metric SET mtr_icon='fas fa-child' WHERE mtr_caption='Matrícula (alumnos) en primarias de educación común';
UPDATE metric SET mtr_icon='fas fa-user-graduate' WHERE mtr_caption='Matrícula (alumnos) en secundarias de educación común';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Secciones (cursos) de nivel inicial común';
UPDATE metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Secciones (cursos) en educación intercultural bilingüe';
UPDATE metric SET mtr_icon='fas fa-chalkboard' WHERE mtr_caption='Secciones (cursos) en primarias de educación común';
UPDATE metric SET mtr_icon='fas fa-chalkboard-teacher' WHERE mtr_caption='Secciones (cursos) en secundarias de educación común';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Fecundidad por grupos de edad';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Tasa de nacimientos por mujer';
UPDATE metric SET mtr_icon='fas fa-wheelchair' WHERE mtr_caption='Discapacidades permanentes';
UPDATE metric SET mtr_icon='fas fa-id-card' WHERE mtr_caption='Cobertura de salud';
UPDATE metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Fallecimientos por grupo de edad';
UPDATE metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Mortalidad general';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Mortalidad infantil';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Natalidad';
UPDATE metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud complementarios';
UPDATE metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud con internación';
UPDATE metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud sin internación';
UPDATE metric SET mtr_icon='fas fa-plus-square' WHERE mtr_caption='Farmacias';
UPDATE metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Centros de desarrollo infantil';
UPDATE metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Vulnerabilidad sanitaria';
UPDATE metric SET mtr_icon='fas fa-industry' WHERE mtr_caption='Tasa de actividad';
UPDATE metric SET mtr_icon='fas fa-user-slash' WHERE mtr_caption='Tasa de desocupación';
UPDATE metric SET mtr_icon='fas fa-industry' WHERE mtr_caption='Tasa de empleo';
UPDATE metric SET mtr_icon='fas fa-hand-holding-usd' WHERE mtr_caption='Jubilaciones y pensiones';
UPDATE metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Bibliotecas';
UPDATE metric SET mtr_icon='fas fa-tv' WHERE mtr_caption='Canales de TV abierta';
UPDATE metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Editoriales de libros';
UPDATE metric SET mtr_icon='fas fa-broadcast-tower' WHERE mtr_caption='Emisoras de radio';
UPDATE metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Ferias del libro';
UPDATE metric SET mtr_icon='fas fa-music' WHERE mtr_caption='Fiestas populares y festivales';
UPDATE metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Librerías';
UPDATE metric SET mtr_icon='fas fa-monument' WHERE mtr_caption='Monumentos y lugares históricos';
UPDATE metric SET mtr_icon='fas fa-landmark' WHERE mtr_caption='Museos y espacios de exhibición patrimonial';
UPDATE metric SET mtr_icon='fas fa-hands-helping' WHERE mtr_caption='Organizaciones sociales culturales';
UPDATE metric SET mtr_icon='fas fa-film' WHERE mtr_caption='Salas de cine';
UPDATE metric SET mtr_icon='fas fa-theater-masks' WHERE mtr_caption='Salas de teatro';
UPDATE metric SET mtr_icon='fas fa-running' WHERE mtr_caption='Establecimientos para actividades deportivas';
UPDATE metric SET mtr_icon='fas fa-place-of-worship' WHERE mtr_caption='Iglesias, templos y lugares de culto';
UPDATE metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Lenguas indígenas por región';
UPDATE metric SET mtr_icon='fas fa-tree' WHERE mtr_caption='Parques Nacionales';
UPDATE metric SET mtr_icon='fas fa-phone' WHERE mtr_caption='Acceso a telefonía pública';
UPDATE metric SET mtr_icon='fas fa-phone' WHERE mtr_caption='Acceso a teléfono de línea';
UPDATE metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Acceso al transporte público';
UPDATE metric SET mtr_icon='fas fa-lightbulb' WHERE mtr_caption='Alumbrado público';
UPDATE metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Recolección de residuos';
UPDATE metric SET mtr_icon='fas fa-fire' WHERE mtr_caption='Acceso a gas de red';
UPDATE metric SET mtr_icon='fas fa-toilet' WHERE mtr_caption='Disposición de excretas';
UPDATE metric SET mtr_icon='fas fa-envelope' WHERE mtr_caption='Oficinas de correo';
UPDATE metric SET mtr_icon='fas fa-university' WHERE mtr_caption='Sucursales bancarias';
UPDATE metric SET mtr_icon='fas fa-train' WHERE mtr_caption='Redes de tren y subterráneo';
UPDATE metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Uso de colectivo por radio censal';
UPDATE metric SET mtr_icon='fas fa-subway' WHERE mtr_caption='Uso de subterráneo por radio censal';
UPDATE metric SET mtr_icon='fas fa-train' WHERE mtr_caption='Uso de tren por radio censal';
UPDATE metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (ballotage)';
UPDATE metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (por orientación comparable)';
UPDATE metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (por partido)';
UPDATE metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Comedores y merenderos comunitarios (Libres del Sur)';
UPDATE metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Organizaciones sociales (Red de Bancos de Alimentos)';
UPDATE metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Comunidades indígenas (INAI)';
UPDATE metric SET mtr_icon='fas fa-place-of-worship' WHERE mtr_caption='Sedes parroquiales de Cáritas';
UPDATE metric SET mtr_icon='fas fa-shield-alt' WHERE mtr_caption='Dependencias policiales, de gendarmería y prefectura';
UPDATE metric SET mtr_icon='fas fa-building' WHERE mtr_caption='Establecimientos penitenciarios';
UPDATE metric SET mtr_icon='fas fa-building' WHERE mtr_caption='Centros clandestinos de detención (1976-1983)';
UPDATE metric SET mtr_icon='fas fa-mountain' WHERE mtr_caption='Altitud (metros)';
UPDATE metric SET mtr_icon='fas fa-cloud-rain' WHERE mtr_caption='Precipitaciones (mm)';
UPDATE metric SET mtr_icon='fas fa-thermometer-half' WHERE mtr_caption='Temperatura media (C°)';
UPDATE metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Basurales (RENABAP)';
UPDATE metric SET mtr_icon='fas fa-trash-alt' WHERE mtr_caption='Microbasurales (RENABAP)';
UPDATE metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Zonas inundables (RENABAP)';
UPDATE metric SET mtr_icon='fas fa-road' WHERE mtr_caption='Pavimento';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Calidad constructiva de la vivienda';
UPDATE metric SET mtr_icon='fas fa-compress-arrows-alt' WHERE mtr_caption='Hacinamiento';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tenencia de la vivienda';
UPDATE metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Zonas inundables';
UPDATE metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Nivel de marginalidad';
UPDATE metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Basurales y rellenos sanitarios';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Countries y barrios cerrados';
UPDATE metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Hogares con déficit habitacional';

UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Barrios populares (RENABAP)';
UPDATE draft_metric SET mtr_icon='fas fa-bolt' WHERE mtr_caption='Modo de acceso a los servicios en Barrios Populares';
UPDATE draft_metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Comedores y merenderos comunitarios (ReNaCoM)';
UPDATE draft_metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Población total';
UPDATE draft_metric SET mtr_icon='fas fa-tint' WHERE mtr_caption='Acceso a agua de red';
UPDATE draft_metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Densidad de población';
UPDATE draft_metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Necesidades básicas insatisfechas (NBI)';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Redes de colectivo';
UPDATE draft_metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Provincias';
UPDATE draft_metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Municipios';
UPDATE draft_metric SET mtr_icon='fas fa-landmark' WHERE mtr_caption='Gobiernos locales';
UPDATE draft_metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Regiones';
UPDATE draft_metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Departamentos';
UPDATE draft_metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Regiones y zonas sanitarias';
UPDATE draft_metric SET mtr_icon='fas fa-mail-bulk' WHERE mtr_caption='Códigos postales (4 dígitos)';
UPDATE draft_metric SET mtr_icon='fas fa-balance-scale' WHERE mtr_caption='Regiones judiciales';
UPDATE draft_metric SET mtr_icon='fas fa-balance-scale' WHERE mtr_caption='Circunscripciones judiciales';
UPDATE draft_metric SET mtr_icon='fas fa-city' WHERE mtr_caption='Aglomerados';
UPDATE draft_metric SET mtr_icon='fas fa-map' WHERE mtr_caption='Zonas del conurbano bonaerense';
UPDATE draft_metric SET mtr_icon='fas fa-map-marker-alt' WHERE mtr_caption='Barrios';
UPDATE draft_metric SET mtr_icon='fas fa-map-pin' WHERE mtr_caption='Localidades';
UPDATE draft_metric SET mtr_icon='fas fa-cloud-sun' WHERE mtr_caption='Climas';
UPDATE draft_metric SET mtr_icon='fas fa-cloud' WHERE mtr_caption='Climas agrupados';
UPDATE draft_metric SET mtr_icon='fas fa-leaf' WHERE mtr_caption='Eco-regiones';
UPDATE draft_metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Sistemas de cuencas';
UPDATE draft_metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Cuencas y regiones hídricas';
UPDATE draft_metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Se reconoce indígena y habla o entiende la lengua de ese pueblo (censo)';
UPDATE draft_metric SET mtr_icon='fas fa-box' WHERE mtr_caption='Disponibilidad de bienes';
UPDATE draft_metric SET mtr_icon='fas fa-broom' WHERE mtr_caption='Hogares con servicio doméstico sin retiro (con cama)';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Jefatura del hogar';
UPDATE draft_metric SET mtr_icon='fas fa-child' WHERE mtr_caption='Niños/as y adolescentes por edad';
UPDATE draft_metric SET mtr_icon='fas fa-user' WHERE mtr_caption='Población adulta por edad';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tamaño de hogar';
UPDATE draft_metric SET mtr_icon='fas fa-venus' WHERE mtr_caption='Tasa de feminidad';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tipo de hogar';
UPDATE draft_metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Población afrodescendiente';
UPDATE draft_metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Población pueblos originarios (censo)';
UPDATE draft_metric SET mtr_icon='fas fa-layer-group' WHERE mtr_caption='Estrato socioeconómico';
UPDATE draft_metric SET mtr_icon='fas fa-exclamation-circle' WHERE mtr_caption='Incidencia del riesgo de exclusión';
UPDATE draft_metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Riesgo de inseguridad alimentaria';
UPDATE draft_metric SET mtr_icon='fas fa-comment' WHERE mtr_caption='Hablan alguna lengua indígena en el hogar';
UPDATE draft_metric SET mtr_icon='fas fa-chart-line' WHERE mtr_caption='Población proyectada por departamento';
UPDATE draft_metric SET mtr_icon='fas fa-coins' WHERE mtr_caption='Pobreza crónica';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Asistencia a educación formal';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Jefes con secundaria completa o más';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Nivel educativo de la población';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Nivel educativo de los jefes';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Niños y adolescentes que no asisten a instituciones educativas formales';
UPDATE draft_metric SET mtr_icon='fas fa-graduation-cap' WHERE mtr_caption='Población mayor de edad sin estudios secundarios completos';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de educación especial';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas primarias de jóvenes y adultos';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de educación especial';
UPDATE draft_metric SET mtr_icon='fas fa-school' WHERE mtr_caption='Escuelas secundarias de jóvenes y adultos';
UPDATE draft_metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Establecimientos con educación intercultural bilingüe';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Establecimientos de nivel inicial común';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Establecimientos de nivel inicial de educación especial';
UPDATE draft_metric SET mtr_icon='fas fa-university' WHERE mtr_caption='Establecimientos de nivel superior';
UPDATE draft_metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Matrícula (alumnos) de educación intercultural bilingüe';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Matrícula (alumnos) de nivel inicial de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-child' WHERE mtr_caption='Matrícula (alumnos) en primarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-user-graduate' WHERE mtr_caption='Matrícula (alumnos) en secundarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Secciones (cursos) de nivel inicial común';
UPDATE draft_metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Secciones (cursos) en educación intercultural bilingüe';
UPDATE draft_metric SET mtr_icon='fas fa-chalkboard' WHERE mtr_caption='Secciones (cursos) en primarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-chalkboard-teacher' WHERE mtr_caption='Secciones (cursos) en secundarias de educación común';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Fecundidad por grupos de edad';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Tasa de nacimientos por mujer';
UPDATE draft_metric SET mtr_icon='fas fa-wheelchair' WHERE mtr_caption='Discapacidades permanentes';
UPDATE draft_metric SET mtr_icon='fas fa-id-card' WHERE mtr_caption='Cobertura de salud';
UPDATE draft_metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Fallecimientos por grupo de edad';
UPDATE draft_metric SET mtr_icon='fas fa-users' WHERE mtr_caption='Mortalidad general';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Mortalidad infantil';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Natalidad';
UPDATE draft_metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud complementarios';
UPDATE draft_metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud con internación';
UPDATE draft_metric SET mtr_icon='fas fa-hospital' WHERE mtr_caption='Establecimientos de salud sin internación';
UPDATE draft_metric SET mtr_icon='fas fa-plus-square' WHERE mtr_caption='Farmacias';
UPDATE draft_metric SET mtr_icon='fas fa-baby' WHERE mtr_caption='Centros de desarrollo infantil';
UPDATE draft_metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Vulnerabilidad sanitaria';
UPDATE draft_metric SET mtr_icon='fas fa-industry' WHERE mtr_caption='Tasa de actividad';
UPDATE draft_metric SET mtr_icon='fas fa-user-slash' WHERE mtr_caption='Tasa de desocupación';
UPDATE draft_metric SET mtr_icon='fas fa-industry' WHERE mtr_caption='Tasa de empleo';
UPDATE draft_metric SET mtr_icon='fas fa-hand-holding-usd' WHERE mtr_caption='Jubilaciones y pensiones';
UPDATE draft_metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Bibliotecas';
UPDATE draft_metric SET mtr_icon='fas fa-tv' WHERE mtr_caption='Canales de TV abierta';
UPDATE draft_metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Editoriales de libros';
UPDATE draft_metric SET mtr_icon='fas fa-broadcast-tower' WHERE mtr_caption='Emisoras de radio';
UPDATE draft_metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Ferias del libro';
UPDATE draft_metric SET mtr_icon='fas fa-music' WHERE mtr_caption='Fiestas populares y festivales';
UPDATE draft_metric SET mtr_icon='fas fa-book-open' WHERE mtr_caption='Librerías';
UPDATE draft_metric SET mtr_icon='fas fa-monument' WHERE mtr_caption='Monumentos y lugares históricos';
UPDATE draft_metric SET mtr_icon='fas fa-landmark' WHERE mtr_caption='Museos y espacios de exhibición patrimonial';
UPDATE draft_metric SET mtr_icon='fas fa-hands-helping' WHERE mtr_caption='Organizaciones sociales culturales';
UPDATE draft_metric SET mtr_icon='fas fa-film' WHERE mtr_caption='Salas de cine';
UPDATE draft_metric SET mtr_icon='fas fa-theater-masks' WHERE mtr_caption='Salas de teatro';
UPDATE draft_metric SET mtr_icon='fas fa-running' WHERE mtr_caption='Establecimientos para actividades deportivas';
UPDATE draft_metric SET mtr_icon='fas fa-place-of-worship' WHERE mtr_caption='Iglesias, templos y lugares de culto';
UPDATE draft_metric SET mtr_icon='fas fa-language' WHERE mtr_caption='Lenguas indígenas por región';
UPDATE draft_metric SET mtr_icon='fas fa-tree' WHERE mtr_caption='Parques Nacionales';
UPDATE draft_metric SET mtr_icon='fas fa-phone' WHERE mtr_caption='Acceso a telefonía pública';
UPDATE draft_metric SET mtr_icon='fas fa-phone' WHERE mtr_caption='Acceso a teléfono de línea';
UPDATE draft_metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Acceso al transporte público';
UPDATE draft_metric SET mtr_icon='fas fa-lightbulb' WHERE mtr_caption='Alumbrado público';
UPDATE draft_metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Recolección de residuos';
UPDATE draft_metric SET mtr_icon='fas fa-fire' WHERE mtr_caption='Acceso a gas de red';
UPDATE draft_metric SET mtr_icon='fas fa-toilet' WHERE mtr_caption='Disposición de excretas';
UPDATE draft_metric SET mtr_icon='fas fa-envelope' WHERE mtr_caption='Oficinas de correo';
UPDATE draft_metric SET mtr_icon='fas fa-university' WHERE mtr_caption='Sucursales bancarias';
UPDATE draft_metric SET mtr_icon='fas fa-train' WHERE mtr_caption='Redes de tren y subterráneo';
UPDATE draft_metric SET mtr_icon='fas fa-bus' WHERE mtr_caption='Uso de colectivo por radio censal';
UPDATE draft_metric SET mtr_icon='fas fa-subway' WHERE mtr_caption='Uso de subterráneo por radio censal';
UPDATE draft_metric SET mtr_icon='fas fa-train' WHERE mtr_caption='Uso de tren por radio censal';
UPDATE draft_metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (ballotage)';
UPDATE draft_metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (por orientación comparable)';
UPDATE draft_metric SET mtr_icon='fas fa-vote-yea' WHERE mtr_caption='Elecciones presidenciales (por partido)';
UPDATE draft_metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Comedores y merenderos comunitarios (Libres del Sur)';
UPDATE draft_metric SET mtr_icon='fas fa-utensils' WHERE mtr_caption='Organizaciones sociales (Red de Bancos de Alimentos)';
UPDATE draft_metric SET mtr_icon='fas fa-feather-alt' WHERE mtr_caption='Comunidades indígenas (INAI)';
UPDATE draft_metric SET mtr_icon='fas fa-place-of-worship' WHERE mtr_caption='Sedes parroquiales de Cáritas';
UPDATE draft_metric SET mtr_icon='fas fa-shield-alt' WHERE mtr_caption='Dependencias policiales, de gendarmería y prefectura';
UPDATE draft_metric SET mtr_icon='fas fa-building' WHERE mtr_caption='Establecimientos penitenciarios';
UPDATE draft_metric SET mtr_icon='fas fa-building' WHERE mtr_caption='Centros clandestinos de detención (1976-1983)';
UPDATE draft_metric SET mtr_icon='fas fa-mountain' WHERE mtr_caption='Altitud (metros)';
UPDATE draft_metric SET mtr_icon='fas fa-cloud-rain' WHERE mtr_caption='Precipitaciones (mm)';
UPDATE draft_metric SET mtr_icon='fas fa-thermometer-half' WHERE mtr_caption='Temperatura media (C°)';
UPDATE draft_metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Basurales (RENABAP)';
UPDATE draft_metric SET mtr_icon='fas fa-trash-alt' WHERE mtr_caption='Microbasurales (RENABAP)';
UPDATE draft_metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Zonas inundables (RENABAP)';
UPDATE draft_metric SET mtr_icon='fas fa-road' WHERE mtr_caption='Pavimento';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Calidad constructiva de la vivienda';
UPDATE draft_metric SET mtr_icon='fas fa-compress-arrows-alt' WHERE mtr_caption='Hacinamiento';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Tenencia de la vivienda';
UPDATE draft_metric SET mtr_icon='fas fa-water' WHERE mtr_caption='Zonas inundables';
UPDATE draft_metric SET mtr_icon='fas fa-exclamation-triangle' WHERE mtr_caption='Nivel de marginalidad';
UPDATE draft_metric SET mtr_icon='fas fa-trash' WHERE mtr_caption='Basurales y rellenos sanitarios';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Countries y barrios cerrados';
UPDATE draft_metric SET mtr_icon='fas fa-home' WHERE mtr_caption='Hogares con déficit habitacional';

UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Barrios populares (RENABAP)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-bolt' WHERE mvw_metric_caption='Modo de acceso a los servicios en Barrios Populares';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-utensils' WHERE mvw_metric_caption='Comedores y merenderos comunitarios (ReNaCoM)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-users' WHERE mvw_metric_caption='Población total';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-tint' WHERE mvw_metric_caption='Acceso a agua de red';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-users' WHERE mvw_metric_caption='Densidad de población';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-exclamation-triangle' WHERE mvw_metric_caption='Necesidades básicas insatisfechas (NBI)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas primarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas secundarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-bus' WHERE mvw_metric_caption='Redes de colectivo';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map' WHERE mvw_metric_caption='Provincias';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map-marker-alt' WHERE mvw_metric_caption='Municipios';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-landmark' WHERE mvw_metric_caption='Gobiernos locales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map' WHERE mvw_metric_caption='Regiones';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map-marker-alt' WHERE mvw_metric_caption='Departamentos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map' WHERE mvw_metric_caption='Regiones y zonas sanitarias';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-mail-bulk' WHERE mvw_metric_caption='Códigos postales (4 dígitos)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-balance-scale' WHERE mvw_metric_caption='Regiones judiciales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-balance-scale' WHERE mvw_metric_caption='Circunscripciones judiciales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-city' WHERE mvw_metric_caption='Aglomerados';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map' WHERE mvw_metric_caption='Zonas del conurbano bonaerense';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map-marker-alt' WHERE mvw_metric_caption='Barrios';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-map-pin' WHERE mvw_metric_caption='Localidades';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-cloud-sun' WHERE mvw_metric_caption='Climas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-cloud' WHERE mvw_metric_caption='Climas agrupados';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-leaf' WHERE mvw_metric_caption='Eco-regiones';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-water' WHERE mvw_metric_caption='Sistemas de cuencas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-water' WHERE mvw_metric_caption='Cuencas y regiones hídricas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-feather-alt' WHERE mvw_metric_caption='Se reconoce indígena y habla o entiende la lengua de ese pueblo (censo)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-box' WHERE mvw_metric_caption='Disponibilidad de bienes';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-broom' WHERE mvw_metric_caption='Hogares con servicio doméstico sin retiro (con cama)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Jefatura del hogar';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-child' WHERE mvw_metric_caption='Niños/as y adolescentes por edad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-user' WHERE mvw_metric_caption='Población adulta por edad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Tamaño de hogar';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-venus' WHERE mvw_metric_caption='Tasa de feminidad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Tipo de hogar';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-users' WHERE mvw_metric_caption='Población afrodescendiente';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-feather-alt' WHERE mvw_metric_caption='Población pueblos originarios (censo)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-layer-group' WHERE mvw_metric_caption='Estrato socioeconómico';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-exclamation-circle' WHERE mvw_metric_caption='Incidencia del riesgo de exclusión';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-exclamation-triangle' WHERE mvw_metric_caption='Riesgo de inseguridad alimentaria';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-comment' WHERE mvw_metric_caption='Hablan alguna lengua indígena en el hogar';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-chart-line' WHERE mvw_metric_caption='Población proyectada por departamento';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-coins' WHERE mvw_metric_caption='Pobreza crónica';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Asistencia a educación formal';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Jefes con secundaria completa o más';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Nivel educativo de la población';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Nivel educativo de los jefes';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Niños y adolescentes que no asisten a instituciones educativas formales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-graduation-cap' WHERE mvw_metric_caption='Población mayor de edad sin estudios secundarios completos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas primarias de educación especial';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas primarias de jóvenes y adultos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas secundarias de educación especial';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-school' WHERE mvw_metric_caption='Escuelas secundarias de jóvenes y adultos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-language' WHERE mvw_metric_caption='Establecimientos con educación intercultural bilingüe';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Establecimientos de nivel inicial común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Establecimientos de nivel inicial de educación especial';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-university' WHERE mvw_metric_caption='Establecimientos de nivel superior';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-language' WHERE mvw_metric_caption='Matrícula (alumnos) de educación intercultural bilingüe';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Matrícula (alumnos) de nivel inicial de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-child' WHERE mvw_metric_caption='Matrícula (alumnos) en primarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-user-graduate' WHERE mvw_metric_caption='Matrícula (alumnos) en secundarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Secciones (cursos) de nivel inicial común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-language' WHERE mvw_metric_caption='Secciones (cursos) en educación intercultural bilingüe';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-chalkboard' WHERE mvw_metric_caption='Secciones (cursos) en primarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-chalkboard-teacher' WHERE mvw_metric_caption='Secciones (cursos) en secundarias de educación común';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Fecundidad por grupos de edad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Tasa de nacimientos por mujer';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-wheelchair' WHERE mvw_metric_caption='Discapacidades permanentes';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-id-card' WHERE mvw_metric_caption='Cobertura de salud';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-users' WHERE mvw_metric_caption='Fallecimientos por grupo de edad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-users' WHERE mvw_metric_caption='Mortalidad general';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Mortalidad infantil';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Natalidad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-hospital' WHERE mvw_metric_caption='Establecimientos de salud complementarios';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-hospital' WHERE mvw_metric_caption='Establecimientos de salud con internación';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-hospital' WHERE mvw_metric_caption='Establecimientos de salud sin internación';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-plus-square' WHERE mvw_metric_caption='Farmacias';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-baby' WHERE mvw_metric_caption='Centros de desarrollo infantil';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-exclamation-triangle' WHERE mvw_metric_caption='Vulnerabilidad sanitaria';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-industry' WHERE mvw_metric_caption='Tasa de actividad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-user-slash' WHERE mvw_metric_caption='Tasa de desocupación';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-industry' WHERE mvw_metric_caption='Tasa de empleo';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-hand-holding-usd' WHERE mvw_metric_caption='Jubilaciones y pensiones';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-book-open' WHERE mvw_metric_caption='Bibliotecas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-tv' WHERE mvw_metric_caption='Canales de TV abierta';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-book-open' WHERE mvw_metric_caption='Editoriales de libros';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-broadcast-tower' WHERE mvw_metric_caption='Emisoras de radio';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-book-open' WHERE mvw_metric_caption='Ferias del libro';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-music' WHERE mvw_metric_caption='Fiestas populares y festivales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-book-open' WHERE mvw_metric_caption='Librerías';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-monument' WHERE mvw_metric_caption='Monumentos y lugares históricos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-landmark' WHERE mvw_metric_caption='Museos y espacios de exhibición patrimonial';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-hands-helping' WHERE mvw_metric_caption='Organizaciones sociales culturales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-film' WHERE mvw_metric_caption='Salas de cine';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-theater-masks' WHERE mvw_metric_caption='Salas de teatro';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-running' WHERE mvw_metric_caption='Establecimientos para actividades deportivas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-place-of-worship' WHERE mvw_metric_caption='Iglesias, templos y lugares de culto';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-language' WHERE mvw_metric_caption='Lenguas indígenas por región';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-tree' WHERE mvw_metric_caption='Parques Nacionales';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-phone' WHERE mvw_metric_caption='Acceso a telefonía pública';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-phone' WHERE mvw_metric_caption='Acceso a teléfono de línea';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-bus' WHERE mvw_metric_caption='Acceso al transporte público';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-lightbulb' WHERE mvw_metric_caption='Alumbrado público';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-trash' WHERE mvw_metric_caption='Recolección de residuos';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-fire' WHERE mvw_metric_caption='Acceso a gas de red';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-toilet' WHERE mvw_metric_caption='Disposición de excretas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-envelope' WHERE mvw_metric_caption='Oficinas de correo';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-university' WHERE mvw_metric_caption='Sucursales bancarias';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-train' WHERE mvw_metric_caption='Redes de tren y subterráneo';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-bus' WHERE mvw_metric_caption='Uso de colectivo por radio censal';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-subway' WHERE mvw_metric_caption='Uso de subterráneo por radio censal';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-train' WHERE mvw_metric_caption='Uso de tren por radio censal';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-vote-yea' WHERE mvw_metric_caption='Elecciones presidenciales (ballotage)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-vote-yea' WHERE mvw_metric_caption='Elecciones presidenciales (por orientación comparable)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-vote-yea' WHERE mvw_metric_caption='Elecciones presidenciales (por partido)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-utensils' WHERE mvw_metric_caption='Comedores y merenderos comunitarios (Libres del Sur)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-utensils' WHERE mvw_metric_caption='Organizaciones sociales (Red de Bancos de Alimentos)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-feather-alt' WHERE mvw_metric_caption='Comunidades indígenas (INAI)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-place-of-worship' WHERE mvw_metric_caption='Sedes parroquiales de Cáritas';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-shield-alt' WHERE mvw_metric_caption='Dependencias policiales, de gendarmería y prefectura';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-building' WHERE mvw_metric_caption='Establecimientos penitenciarios';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-building' WHERE mvw_metric_caption='Centros clandestinos de detención (1976-1983)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-mountain' WHERE mvw_metric_caption='Altitud (metros)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-cloud-rain' WHERE mvw_metric_caption='Precipitaciones (mm)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-thermometer-half' WHERE mvw_metric_caption='Temperatura media (C°)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-trash' WHERE mvw_metric_caption='Basurales (RENABAP)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-trash-alt' WHERE mvw_metric_caption='Microbasurales (RENABAP)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-water' WHERE mvw_metric_caption='Zonas inundables (RENABAP)';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-road' WHERE mvw_metric_caption='Pavimento';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Calidad constructiva de la vivienda';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-compress-arrows-alt' WHERE mvw_metric_caption='Hacinamiento';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Tenencia de la vivienda';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-water' WHERE mvw_metric_caption='Zonas inundables';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-exclamation-triangle' WHERE mvw_metric_caption='Nivel de marginalidad';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-trash' WHERE mvw_metric_caption='Basurales y rellenos sanitarios';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Countries y barrios cerrados';
UPDATE snapshot_metric_version SET mvw_metric_icon='fas fa-home' WHERE mvw_metric_caption='Hogares con déficit habitacional';

UPDATE version SET ver_value = '133' WHERE ver_name = 'DB';
